version: '3.7'
services:
  nginx:
    container_name: core_web
    restart: on-failure
    image: nginx:stable
    environment:
      - EC2_HOST_DNS=${EC2_HOST_DNS}
    volumes:
      - ./nginx/user_conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    container_name: core_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - EC2_HOST_DNS=${EC2_HOST_DNS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - "5000:5000"
    command: >
      sh -c " python manage.py migrate &&
          gunicorn CoreRoot.wsgi:application --bind 0.0.0.0:5000"
    volumes:
     - .:/app
     - static_volume:/app/static
    depends_on:
     - db
  db:
    container_name: core_db
    image: postgres:12.0-alpine
    environment:
      - EC2_HOST_DNS=${EC2_HOST_DNS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # init_db:
  #   image: postgres:12.0-alpine
  #   command: >
  #     sh -c "
  #       sleep 5 &&
  #       psql -h db -U ${DB_USER} -d ${DB_NAME} -c 'CREATE DATABASE coredb;' &&
  #       psql -h db -U ${DB_USER} -d ${DB_NAME} -c \"CREATE USER core WITH PASSWORD '12345678';\" &&
  #       psql -h db -U ${DB_USER} -d ${DB_NAME} -c 'GRANT ALL PRIVILEGES ON DATABASE coredb TO core;'"
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_NAME=coredb


volumes:
  static_volume:
  postgres_data: